[versions]
spock = "2.3-groovy-3.0"
junit = "5.11.3"
javalin = "6.3.0"
mockito = "5.14.2"
java-debug = "0.52.0"
mixin = "0.15.5+mixin.0.8.7"

gradle-nightly = "8.12-20241110002642+0000"
leaf-loader = "0.1.0"
leaf-installer = "0.1.0"

[libraries]
spock = { module = "org.spockframework:spock-core", version.ref = "spock" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
java-debug = { module = "com.microsoft.java:com.microsoft.java.debug.core", version.ref = "java-debug" }
mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
gradle-nightly = { module = "org.gradle:dummy", version.ref = "gradle-nightly" }
leaf-loader = { module = "dev.aoqia:leaf-loader", version.ref = "leaf-loader" }
leaf-installer = { module = "dev.aoqia:leaf-installer", version.ref = "leaf-installer" }
