name: build
on:
  push:
  pull_request:
  workflow_call:
  workflow_run:
    workflows:
    - manual
    branches:
      - main
      - dev
    types:
      - requested

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4
      - name: Check
        run: "./gradlew check -x test"
      - name: Build
        run: "./gradlew build -x test --stacktrace"
