name: CommitLint

on: [ push, pull_request ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          pnpm --version
          pnpm commitlint --version

      - name: Install commitlint
        run: |
          pnpm add --save-dev @commitlint/{cli,config-conventional}
          echo "export default { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js

      - name: Validate current commit (last)
        if: github.event_name == 'push'
        run: pnpm commitlint --last --verbose

      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
