name: deploy-dry
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: build
    uses: .github/workflows/build.yml
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Stage Plugin
        run: "./gradlew publish"
      - name: Dry Deploy Plugin
        run: "./gradlew jreleaserFullRelease"
        env:
          JRELEASER_DRY_RUN: true
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE_KEY: ${{ secrets.GPG_PASSPHRASE_KEY }}
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
      - name: Dry Deploy Plugin and Plugin Marker to Gradle Plugin Portal
        run: "./gradlew publishPlugins --validate-only"
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
