name: Publish Dry
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
      - name: Execute Gradle Check
        run: "./gradlew clean check -x test"
      - name: Execute JReleaser Config Check
        run: "./gradlew jreleaserConfig"
      - name: Build
        run: "./gradlew build -x test --stracktrace"
      - name: Publish
        run: "./gradlew build jreleaserFullRelease -Djreleaser.dry.run=true -x test --stacktrace"
        env:
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE_KEY: ${{ secrets.GPG_PASSPHRASE_KEY }}
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
