name: Publish Dry
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gradle wrapper validation
        uses: gradle/actions/wrapper-validation@v3
      - name: Build and publish Loom
        run: ./gradlew build jreleaserFullRelease -x test --stacktrace
        env:
          MAVEN_URL: ${{ secrets.CENTRAL_URL }}
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
