name: Publish Dry
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4
      - name: Verify Jreleaser Configuration
        run: "./gradlew jreleaserConfig"
        env:
          JRELEASER_DRY_RUN: true
      - name: Clean and Check
        run: "./gradlew clean check -x test"
      - name: Build
        run: "./gradlew build -x test"
      - name: Stage Plugin
        run: "./gradlew publishPluginMavenPublicationToMavenRepository"
      - name: Dry Deploy Plugin
        run: "./gradlew jreleaserFullRelease"
        env:
          JRELEASER_DRY_RUN: true
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE_KEY: ${{ secrets.GPG_PASSPHRASE_KEY }}
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
      - name: Stage Plugin Marker
        run: "./gradlew publishLeafLoomPluginMarkerMavenPublicationToMavenRepository"
      - name: Dry Deploy Plugin and Plugin Marker to Gradle Plugin Portal
        run: "./gradlew publishPlugins --validate-only"
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
